ENTRY(_start)
SECTIONS {
    . = 0x40100000; /* RAM starts at 0x40000000 but if we ask to load the kernel there, QEMU will not load a DTB */
    .text : {
        *(.text.boot)
        *(.text)
         }
    .data : { *(.data) }
    .bss : {
        __bss_start = .;
        *(.bss)
        __bss_end = .;
         }
    . = ALIGN(16); /* two times pointer size */
    . += 0x1000; /* 4kB of stack memory */
    stack_top = .;
}
